// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHistory(arg1) {
  return window['go']['handlers']['Base64Handler']['AddHistory'](arg1);
}

export function ClearHistory() {
  return window['go']['handlers']['Base64Handler']['ClearHistory']();
}

export function Decode(arg1) {
  return window['go']['handlers']['Base64Handler']['Decode'](arg1);
}

export function DecodeURLSafe(arg1) {
  return window['go']['handlers']['Base64Handler']['DecodeURLSafe'](arg1);
}

export function Encode(arg1) {
  return window['go']['handlers']['Base64Handler']['Encode'](arg1);
}

export function EncodeURLSafe(arg1) {
  return window['go']['handlers']['Base64Handler']['EncodeURLSafe'](arg1);
}

export function ListHistory() {
  return window['go']['handlers']['Base64Handler']['ListHistory']();
}

export function Validate(arg1) {
  return window['go']['handlers']['Base64Handler']['Validate'](arg1);
}

export function ValidateURLSafe(arg1) {
  return window['go']['handlers']['Base64Handler']['ValidateURLSafe'](arg1);
}
