// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function AddHistory(arg1:domain.ToolHistoryRecord):Promise<Array<domain.ToolHistoryRecord>>;

export function ClearHistory():Promise<void>;

export function HashFile(arg1:string,arg2:string):Promise<string>;

export function HashText(arg1:string,arg2:string):Promise<string>;

export function ListHistory():Promise<Array<domain.ToolHistoryRecord>>;

export function OpenFileDialog():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;
