// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHistory(arg1) {
  return window['go']['handlers']['HashHandler']['AddHistory'](arg1);
}

export function ClearHistory() {
  return window['go']['handlers']['HashHandler']['ClearHistory']();
}

export function HashFile(arg1, arg2) {
  return window['go']['handlers']['HashHandler']['HashFile'](arg1, arg2);
}

export function HashText(arg1, arg2) {
  return window['go']['handlers']['HashHandler']['HashText'](arg1, arg2);
}

export function ListHistory() {
  return window['go']['handlers']['HashHandler']['ListHistory']();
}

export function OpenFileDialog() {
  return window['go']['handlers']['HashHandler']['OpenFileDialog']();
}

export function SetContext(arg1) {
  return window['go']['handlers']['HashHandler']['SetContext'](arg1);
}
