// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHistory(arg1) {
  return window['go']['handlers']['IPQueryHandler']['AddHistory'](arg1);
}

export function ClearHistory() {
  return window['go']['handlers']['IPQueryHandler']['ClearHistory']();
}

export function ListHistory() {
  return window['go']['handlers']['IPQueryHandler']['ListHistory']();
}

export function Query(arg1) {
  return window['go']['handlers']['IPQueryHandler']['Query'](arg1);
}

export function QueryBatch(arg1) {
  return window['go']['handlers']['IPQueryHandler']['QueryBatch'](arg1);
}
