// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Format(arg1) {
  return window['go']['handlers']['JSONHandler']['Format'](arg1);
}

export function FormatWithEscape(arg1, arg2) {
  return window['go']['handlers']['JSONHandler']['FormatWithEscape'](arg1, arg2);
}

export function FromYAML(arg1) {
  return window['go']['handlers']['JSONHandler']['FromYAML'](arg1);
}

export function Minify(arg1) {
  return window['go']['handlers']['JSONHandler']['Minify'](arg1);
}

export function ToYAML(arg1) {
  return window['go']['handlers']['JSONHandler']['ToYAML'](arg1);
}

export function Validate(arg1) {
  return window['go']['handlers']['JSONHandler']['Validate'](arg1);
}
