// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Format(arg1:string):Promise<string>;

export function FormatWithEscape(arg1:string,arg2:boolean):Promise<string>;

export function FromYAML(arg1:string):Promise<string>;

export function Minify(arg1:string):Promise<string>;

export function SaveFileDialog(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function ToYAML(arg1:string):Promise<string>;

export function Validate(arg1:string):Promise<boolean>;
