// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Generate(arg1:string,arg2:string):Promise<string>;

export function GenerateImage(arg1:string,arg2:string):Promise<Array<number>>;
