// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AddHistory(arg1:domain.ToolHistoryRecord):Promise<Array<domain.ToolHistoryRecord>>;

export function ClearHistory():Promise<void>;

export function Generate(arg1:string,arg2:string):Promise<string>;

export function GenerateImage(arg1:string,arg2:string):Promise<Array<number>>;

export function ListHistory():Promise<Array<domain.ToolHistoryRecord>>;
