// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHistory(arg1) {
  return window['go']['handlers']['QRCodeHandler']['AddHistory'](arg1);
}

export function ClearHistory() {
  return window['go']['handlers']['QRCodeHandler']['ClearHistory']();
}

export function Generate(arg1, arg2) {
  return window['go']['handlers']['QRCodeHandler']['Generate'](arg1, arg2);
}

export function GenerateImage(arg1, arg2) {
  return window['go']['handlers']['QRCodeHandler']['GenerateImage'](arg1, arg2);
}

export function ListHistory() {
  return window['go']['handlers']['QRCodeHandler']['ListHistory']();
}
