// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Generate(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['handlers']['RandomStringHandler']['Generate'](arg1, arg2, arg3, arg4, arg5);
}

export function GenerateBatch(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['handlers']['RandomStringHandler']['GenerateBatch'](arg1, arg2, arg3, arg4, arg5, arg6);
}
