// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AddHistory(arg1:domain.ToolHistoryRecord):Promise<Array<domain.ToolHistoryRecord>>;

export function ClearHistory():Promise<void>;

export function Generate(arg1:number,arg2:boolean,arg3:boolean,arg4:boolean,arg5:boolean):Promise<string>;

export function GenerateBatch(arg1:number,arg2:boolean,arg3:boolean,arg4:boolean,arg5:boolean,arg6:number):Promise<Array<string>>;

export function ListHistory():Promise<Array<domain.ToolHistoryRecord>>;
