// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTheme() {
  return window['go']['handlers']['ThemeHandler']['GetTheme']();
}

export function LoadTheme() {
  return window['go']['handlers']['ThemeHandler']['LoadTheme']();
}

export function SetTheme(arg1) {
  return window['go']['handlers']['ThemeHandler']['SetTheme'](arg1);
}
