// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FormatNow(arg1:string):Promise<string>;

export function GetCurrentTimestamp():Promise<number>;

export function GetCurrentTimestampMilli():Promise<number>;

export function TimeStringToTimestamp(arg1:string,arg2:string):Promise<number>;

export function TimeStringToTimestampMilli(arg1:string,arg2:string):Promise<number>;

export function TimestampToTimeString(arg1:number,arg2:string):Promise<string>;

export function TimestampToTimeStringMilli(arg1:number,arg2:string):Promise<string>;
