// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AddTimestampHistory(arg1:domain.HistoryRecord):Promise<Array<domain.HistoryRecord>>;

export function ClearTimestampHistory():Promise<void>;

export function FormatNow(arg1:string,arg2:string):Promise<string>;

export function GetCurrentTimestamp():Promise<number>;

export function GetCurrentTimestampMilli():Promise<number>;

export function ListTimestampHistory():Promise<Array<domain.HistoryRecord>>;

export function TimeStringToTimestamp(arg1:string,arg2:string,arg3:string):Promise<number>;

export function TimeStringToTimestampMilli(arg1:string,arg2:string,arg3:string):Promise<number>;

export function TimestampToTimeString(arg1:number,arg2:string,arg3:string):Promise<string>;

export function TimestampToTimeStringMilli(arg1:number,arg2:string,arg3:string):Promise<string>;
