// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FormatNow(arg1) {
  return window['go']['handlers']['TimestampHandler']['FormatNow'](arg1);
}

export function GetCurrentTimestamp() {
  return window['go']['handlers']['TimestampHandler']['GetCurrentTimestamp']();
}

export function GetCurrentTimestampMilli() {
  return window['go']['handlers']['TimestampHandler']['GetCurrentTimestampMilli']();
}

export function TimeStringToTimestamp(arg1, arg2) {
  return window['go']['handlers']['TimestampHandler']['TimeStringToTimestamp'](arg1, arg2);
}

export function TimeStringToTimestampMilli(arg1, arg2) {
  return window['go']['handlers']['TimestampHandler']['TimeStringToTimestampMilli'](arg1, arg2);
}

export function TimestampToTimeString(arg1, arg2) {
  return window['go']['handlers']['TimestampHandler']['TimestampToTimeString'](arg1, arg2);
}

export function TimestampToTimeStringMilli(arg1, arg2) {
  return window['go']['handlers']['TimestampHandler']['TimestampToTimeStringMilli'](arg1, arg2);
}
