// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultProvider() {
  return window['go']['handlers']['TranslateHandler']['GetDefaultProvider']();
}

export function GetProviderConfig(arg1) {
  return window['go']['handlers']['TranslateHandler']['GetProviderConfig'](arg1);
}

export function GetProviders() {
  return window['go']['handlers']['TranslateHandler']['GetProviders']();
}

export function SaveProviderConfig(arg1, arg2) {
  return window['go']['handlers']['TranslateHandler']['SaveProviderConfig'](arg1, arg2);
}

export function SetDefaultProvider(arg1) {
  return window['go']['handlers']['TranslateHandler']['SetDefaultProvider'](arg1);
}

export function Translate(arg1, arg2, arg3) {
  return window['go']['handlers']['TranslateHandler']['Translate'](arg1, arg2, arg3);
}
