// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultProvider():Promise<string>;

export function GetProviderConfig(arg1:string):Promise<string>;

export function GetProviders():Promise<string>;

export function SaveProviderConfig(arg1:string,arg2:string):Promise<void>;

export function SetDefaultProvider(arg1:string):Promise<void>;

export function Translate(arg1:string,arg2:string,arg3:string):Promise<string>;
