// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHistory(arg1) {
  return window['go']['handlers']['URLHandler']['AddHistory'](arg1);
}

export function ClearHistory() {
  return window['go']['handlers']['URLHandler']['ClearHistory']();
}

export function Decode(arg1) {
  return window['go']['handlers']['URLHandler']['Decode'](arg1);
}

export function Encode(arg1) {
  return window['go']['handlers']['URLHandler']['Encode'](arg1);
}

export function ListHistory() {
  return window['go']['handlers']['URLHandler']['ListHistory']();
}
