// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AddHistory(arg1:domain.ToolHistoryRecord):Promise<Array<domain.ToolHistoryRecord>>;

export function ClearHistory():Promise<void>;

export function Decode(arg1:string):Promise<string>;

export function Encode(arg1:string):Promise<string>;

export function ListHistory():Promise<Array<domain.ToolHistoryRecord>>;
