// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateBatch(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['UUIDHandler']['GenerateBatch'](arg1, arg2, arg3, arg4);
}

export function GenerateV1() {
  return window['go']['handlers']['UUIDHandler']['GenerateV1']();
}

export function GenerateV3(arg1, arg2) {
  return window['go']['handlers']['UUIDHandler']['GenerateV3'](arg1, arg2);
}

export function GenerateV4() {
  return window['go']['handlers']['UUIDHandler']['GenerateV4']();
}

export function GenerateV5(arg1, arg2) {
  return window['go']['handlers']['UUIDHandler']['GenerateV5'](arg1, arg2);
}
