// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AddHistory(arg1:domain.ToolHistoryRecord):Promise<Array<domain.ToolHistoryRecord>>;

export function ClearHistory():Promise<void>;

export function GenerateBatch(arg1:string,arg2:number,arg3:string,arg4:string):Promise<Array<string>>;

export function GenerateV1():Promise<string>;

export function GenerateV3(arg1:string,arg2:string):Promise<string>;

export function GenerateV4():Promise<string>;

export function GenerateV5(arg1:string,arg2:string):Promise<string>;

export function GenerateV7():Promise<string>;

export function ListHistory():Promise<Array<domain.ToolHistoryRecord>>;
