// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearInitialTool():Promise<void>;

export function GetCurrentTool():Promise<string>;

export function GetInitialTool():Promise<string>;

export function GetTheme():Promise<string>;

export function GetVersion():Promise<string>;

export function LoadThemeForStartup():Promise<void>;

export function NavigateToTool(arg1:string):Promise<boolean>;

export function NextTool():Promise<void>;

export function PreviousTool():Promise<void>;

export function SetCurrentTool(arg1:string):Promise<void>;

export function SetInitialTool(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function ShowHelp():Promise<void>;
