// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInitialTool():Promise<string>;

export function GetVersion():Promise<string>;

export function NavigateToTool(arg1:string):Promise<boolean>;

export function SetInitialTool(arg1:string):Promise<void>;
