// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearInitialTool() {
  return window['go']['app']['App']['ClearInitialTool']();
}

export function GetCurrentTool() {
  return window['go']['app']['App']['GetCurrentTool']();
}

export function GetInitialTool() {
  return window['go']['app']['App']['GetInitialTool']();
}

export function GetTheme() {
  return window['go']['app']['App']['GetTheme']();
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function LoadThemeForStartup() {
  return window['go']['app']['App']['LoadThemeForStartup']();
}

export function NavigateToTool(arg1) {
  return window['go']['app']['App']['NavigateToTool'](arg1);
}

export function NextTool() {
  return window['go']['app']['App']['NextTool']();
}

export function PreviousTool() {
  return window['go']['app']['App']['PreviousTool']();
}

export function SetCurrentTool(arg1) {
  return window['go']['app']['App']['SetCurrentTool'](arg1);
}

export function SetInitialTool(arg1) {
  return window['go']['app']['App']['SetInitialTool'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['app']['App']['SetTheme'](arg1);
}

export function ShowHelp() {
  return window['go']['app']['App']['ShowHelp']();
}
