// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearInitialTool() {
  return window['go']['app']['App']['ClearInitialTool']();
}

export function GetInitialTool() {
  return window['go']['app']['App']['GetInitialTool']();
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function NavigateToTool(arg1) {
  return window['go']['app']['App']['NavigateToTool'](arg1);
}

export function SetInitialTool(arg1) {
  return window['go']['app']['App']['SetInitialTool'](arg1);
}
